name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    env:
      TAG: xmrig/xmrig

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

      
    - name: Download cbctl binary
      run: wget https://setup.containers.carbonblack.io/cbctl/v1.9.1/linux/cbctl && chmod +x cbctl
      
    - name: Run Image Scan with cbctl binary
      run: ./cbctl image scan $TAG --cb-api-key ${{ secrets.CBCTL_CB_API_KEY }} --cb-api-id ${{ secrets.CBCTL_CB_API_ID }}  --org-key ${{ secrets.CBCTL_ORG_KEY }} --saas-url ${{ secrets.CBCTL_SAAS_URL }}
      
      
